# Generated by Django 3.0.6 on 2020-05-22 17:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BugTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('file_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in progress', 'In progress'), ('complete', 'Complete'), ('invalid', 'Invalid')], default='open', max_length=11)),
                ('is_invalid', models.BooleanField(default=False)),
            ],
        ),
    ]
